# Generated by Django 4.2.6 on 2023-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Вы хотите опубликовать эту запись?', verbose_name='Опубликовано'),
        ),
    ]
