# Generated by Django 4.2.6 on 2023-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='posts',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
