# Generated by Django 4.2.6 on 2023-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_posts_image2_posts_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selected_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
