# Generated by Django 4.2.6 on 2023-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_slug_posts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='url',
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
