# Generated by Django 4.2.6 on 2023-11-25 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
