# Generated by Django 4.2.6 on 2023-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_posts_slug_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
