# Generated by Django 4.2.6 on 2023-11-25 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.SlugField(default=uuid.uuid1, max_length=100, verbose_name='Автор'),
        ),
    ]
