# Generated by Django 4.2.6 on 2023-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Автор'),
        ),
    ]
