# Generated by Django 4.2.6 on 2023-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
