# Generated by Django 4.2.6 on 2024-02-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_ban_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban_words',
            options={'verbose_name': 'Фильтры слов', 'verbose_name_plural': 'Фильтры слов'},
        ),
    ]
